import { Action } from 'redux'

export interface ActionWithPayload<T> extends Action {
  payload: T
}

export enum BOOK_ACTION {
  FETCH_BOOK = 'FETCH_BOOK',
  FETCH_BOOK_FULFILLED = 'FETCH_BOOK_FULFILLED',
  FETCH_BOOK_FAILURE = 'FETCH_BOOK_FAILURE',

  TOGGLE_LIKE = 'TOGGLE_LIKE',
  TOGGLE_LIKE_FULFILLED = 'TOGGLE_LIKE_FULFILLED',
  TOGGLE_LIKE_FAILURE = 'TOGGLE_LIKE_FAILURE',

  GET_LIKE_LIST = 'GET_LIKE_LIST',
  GET_LIKE_LIST_FULFILLED = 'GET_LIKE_LIST_FULFILLED',
  GET_LIKE_LIST_FAILURE = 'GET_LIKE_LIST_FAILURE',
}
